Allow reindeer configuration without DEFAULT universe
Summary:
Previously, if specifying >0 universes in reindeer.toml, it was necessary for one of them to be called `DEFAULT`.

```lang=toml
# reindeer.toml

[universe.DEFAULT]
constraint = "DEFAULT"

[universe.bootstrap]
constraints = "//constraints:bootstrap"
include_crates = [
    ...
]
```

If you did not put a DEFAULT universe, reindeer would crash.

```lang=text,counterexample
thread 'main' panicked at src/universe.rs:180:59:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

However, nothing in reindeer's universe implementation depends meaningfully on there being a DEFAULT universe. The code with the crash only needs *some* arbitrary universe to begin merging the rest of the universes' rules into. Universe merging is commutative so this can begin with any universe.

Reviewed By: JakobDegen

Differential Revision: D73322989

fbshipit-source-id: b0ceed03e555b16c9e89dbf44eaa137659971236