Suppress await_holding_refcell_ref clippy lint on SharedSource
Summary:
As far as I can tell, this code is fine as-is. The only use of `self.delegate.borrow_mut()` is in `Source::set_quiet` and Cargo would only call `set_quiet` very early after obtaining a source, not interleaved with awaiting queries and downloads.

```lang=log
warning: this `RefCell` reference is held across an await point
   --> fbcode/common/rust/tools/reindeer/src/cargo.rs:326:9
    |
326 |         self.delegate.borrow().query(dep, kind, f).await
    |         ^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: ensure the reference is dropped before calling `await`
note: these are all the await points this reference is held through
   --> fbcode/common/rust/tools/reindeer/src/cargo.rs:326:52
    |
326 |         self.delegate.borrow().query(dep, kind, f).await
    |                                                    ^^^^^
    = help: for further information visit https://rust-lang.github.io/rust-clippy/rust-1.97.0/index.html#await_holding_refcell_ref
    = note: `#[warn(clippy::await_holding_refcell_ref)]` on by default

warning: this `RefCell` reference is held across an await point
   --> fbcode/common/rust/tools/reindeer/src/cargo.rs:341:9
    |
341 |         self.delegate.borrow().download(pkg_id).await
    |         ^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: ensure the reference is dropped before calling `await`
note: these are all the await points this reference is held through
   --> fbcode/common/rust/tools/reindeer/src/cargo.rs:341:49
    |
341 |         self.delegate.borrow().download(pkg_id).await
    |                                                 ^^^^^
    = help: for further information visit https://rust-lang.github.io/rust-clippy/rust-1.97.0/index.html#await_holding_refcell_ref

warning: this `RefCell` reference is held across an await point
   --> fbcode/common/rust/tools/reindeer/src/cargo.rs:349:9
    |
349 | /         self.delegate
350 | |             .borrow()
    | |_____________________^
    |
    = help: ensure the reference is dropped before calling `await`
note: these are all the await points this reference is held through
   --> fbcode/common/rust/tools/reindeer/src/cargo.rs:352:14
    |
352 |             .await
    |              ^^^^^
    = help: for further information visit https://rust-lang.github.io/rust-clippy/rust-1.97.0/index.html#await_holding_refcell_ref

warning: this `RefCell` reference is held across an await point
   --> fbcode/common/rust/tools/reindeer/src/cargo.rs:372:9
    |
372 |         self.delegate.borrow().is_yanked(pkg).await
    |         ^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: ensure the reference is dropped before calling `await`
note: these are all the await points this reference is held through
   --> fbcode/common/rust/tools/reindeer/src/cargo.rs:372:47
    |
372 |         self.delegate.borrow().is_yanked(pkg).await
    |                                               ^^^^^
    = help: for further information visit https://rust-lang.github.io/rust-clippy/rust-1.97.0/index.html#await_holding_refcell_ref
```

Dropping the RefCell reference early as recommended by the clippy lint is not possible in this case.

```lang=log,counterexample
error[E0716]: temporary value dropped while borrowed
   --> fbcode/common/rust/tools/reindeer/src/cargo.rs:326:19
    |
326 |         let fut = self.delegate.borrow().query(dep, kind, f);
    |                   ^^^^^^^^^^^^^^^^^^^^^^                    - temporary value is freed at the end of this statement
    |                   |
    |                   creates a temporary value which is freed while still in use
327 |         fut.await
    |         --- borrow later used here
    |
    = note: consider using a `let` binding to create a longer lived value
```

Differential Revision: D118750058

fbshipit-source-id: 83ed5c79b7e40e540e61afa4c73ac9be59fe5672