Delete `reindeer update` subcommand
Summary:
This subcommand was introduced in reindeer commit number 1 ({D16605360}) and was last useful a long time ago when the repo was small. These days, simultaneously updating every third-party crate is unlikely to work and is never what we would want, and its role is superseded by Crate Captain ({D91373788}).

Trying to run `fbcode/common/rust/tools/reindeer/reindeer --third-party-dir=third-party/rust update` today fails like this:

```lang=log,counterexample
[ERROR reindeer] `CARGO_HOME="/data/users/dtolnay/fbsource/third-party/rust/.cargo" RUSTC="/data/users/dtolnay/fbsource/third-party/rust/../../xplat/rust/toolchain/current/basic/bin/rustc" RUSTC_BOOTSTRAP="1" "/data/users/dtolnay/fbsource/third-party/rust/../../xplat/rust/toolchain/current/basic/bin/cargo" "generate-lockfile" "--manifest-path" "/data/users/dtolnay/fbsource/third-party/rust/Cargo.toml" "-Zbindeps"` failed:
    error: failed to load source for dependency `finl_unicode`

    Caused by:
      unable to update https://github.com/dahosek/finl_unicode.git?rev=a1892f26245529f2ef3877a9ebd610c96cec07a6

    Caused by:
      the source git+https://github.com/dahosek/finl_unicode.git?rev=a1892f26245529f2ef3877a9ebd610c96cec07a6 requires a lock file to be present first before it can be
      used against vendored source code

      remove the source replacement configuration, generate a lock file, and then
      restore the source replacement configuration to continue the build
```

Reviewed By: diliop

Differential Revision: D110631306

fbshipit-source-id: b7e477aa4e766732a01ca1f977a1753a78cea694