Make buckify automatically detect whether vendoring is used
Summary:
Previously, if you ran `reindeer buckify` without `reindeer vendor`, without having `vendor = false` in the reindeer.toml, then it would fail in the following meaningless way:

```
[ERROR reindeer] parsing metadata

    Caused by:
        0: running cargo
        1: cargo metadata --format-version 1 --manifest-path /git/cxx/third-party/Cargo.toml --frozen --locked --offline failed:
           error: failed to get `cc` as a dependency of package `third-party v0.0.0 (/git/cxx/third-party)`

           Caused by:
             failed to load source for dependency `cc`

           Caused by:
             Unable to update registry `crates-io`

           Caused by:
             failed to update replaced source registry `crates-io`

           Caused by:
             failed to read root of directory source: /git/cxx/third-party/vendor

           Caused by:
             No such file or directory (os error 2)
```

After this diff, it will succeed and behave like `vendor = false`. In other words, without messing with config, you can run `reindeer vendor` + `reindeer buckify` to get vendored targets, and you can run just `reindeer buckify` to get non-vendored targets.

Reviewed By: zertosh

Differential Revision: D47317816

fbshipit-source-id: bc964217e72ddfe32ea2566554d182077f526c9f