Enable toml preserve_order feature
Summary:
This was landed earlier this year by accident in {D67542150}, then reverted in {D68064760} due to test breakages.

I have fixed the tests observed to have been broken in T212417779. There were only two.

For toml 0.8, this feature is not terribly significant. However, toml 0.9 performs more internal buffering using `toml::map::Map`, so the choice of map representation makes a big difference. For example, for the following `linttool` test it is critical that tables are deserialized with order preserved because the order of the remap operations is significant. Toml 0.8 did that with or without the "preserve_order" feature, but toml 0.9 does not.

https://www.internalfb.com/code/fbsource/[0074b9b9f65376c0937e0bf4476086542ef5dc88]/fbcode/linttool/linttool/src/core/ide/ide_severity_remap.rs?lines=76-81%2C84-85%2C100-103

```lang=toml,counterexample
✗ Fail: linttool/linttool:linttool-unittest - core::ide::ide_severity_remap::tests::test_apply (0.5s)
thread 'core::ide::ide_severity_remap::tests::test_apply' panicked at fbcode/linttool/linttool/src/core/ide/ide_severity_remap.rs:103:9:
assertion `left == right` failed
  left: Disabled
 right: Warning
```

This unblocks {D78189404}.

Reviewed By: diliop

Differential Revision: D78204628

fbshipit-source-id: 465dfdaecd58bf0829215fafd71fcbc3d11d5c88