updating ctrlc from 3.4.0 to 3.4.5 for panic handling
Summary:
updating ctrlc from 3.4.0 to 3.4.5 for panic handling

one of the consistent error groupings in the "Hargow Infrastructure Failure Impact" alarm is thread 'main' panicked at 'failed to spawn thread: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', third-party/rust/vendor/ctrlc-3.4.0/src/lib.rs:150:10

looks like a persistent problem that's been happening as far as back as our logs go https://fburl.com/scuba/hargow/ae4nvino

the code in question calls an expect() which sometimes fails to createa thread, panicing the app
good news, this is [fixed upstream](https://github.com/Detegr/rust-ctrlc/commit/b543abe6c25bd54754bbbbcfcff566e046f8e609) by swapping the expect with a map_err

Reviewed By: wtetzner, mbassale, dtolnay

Differential Revision: D62211602

fbshipit-source-id: 5242bf426bfd5d733f1842d75836e63e45d04a1f