Fix backslashed paths ending up in mapped_srcs on Windows
Summary:
Via user report in Discord.

```
Error running analysis for `root//:buck2 (prelude//platforms:default#fb50fd37ce946800)`

Caused by:
    0: Error looking up configured node root//:buck2 (prelude//platforms:default#fb50fd37ce946800)
    1: Error looking up configured node root//app/buck2:buck2-bin (prelude//platforms:default#fb50fd37ce946800)
    2: Error looking up configured node shim//third-party/rust:anyhow (prelude//platforms:default#fb50fd37ce946800)
    3: looking up unconfigured target node `shim//third-party/rust:anyhow`
    4: Error loading targets in package `shim//third-party/rust` for target `shim//third-party/rust:anyhow`
    5: Error evaluating build file: `shim//third-party/rust:BUCK`
    6: Traceback (most recent call last):
         * shim/third-party/rust/BUCK:8370, in <module>
             cargo.rust_library(
         * prelude/rust/cargo_package.bzl:94, in _cargo_rust_library
             native.rust_library(name = name, **kwargs)
       error: Error coercing attribute `mapped_srcs` of `shim//third-party/rust:libsqlite3-sys-0.25.2`
         --> prelude/rust/cargo_package.bzl:94:5
          |
       94 |     native.rust_library(name = name, **kwargs)
          |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          |

       Error coercing attribute `mapped_srcs` of `shim//third-party/rust:libsqlite3-sys-0.25.2`

       Caused by:
           0: Error coercing attribute `mapped_srcs` of type `attrs.dict(attrs.source(), attrs.string(), sorted=false, default={})`
           1: Error coercing {"vendor\\libsqlite3-sys-0.25.2\\sqlite3/bindgen_bundled_version.rs": "vendor/libsqlite3-sys-0.25.2/src/bindgen.rs"}
           2: Error coercing "vendor\\libsqlite3-sys-0.25.2\\sqlite3/bindgen_bundled_version.rs"
           3: Couldn't coerce `vendor\libsqlite3-sys-0.25.2\sqlite3/bindgen_bundled_version.rs` as a source.
                Error when treated as a target: Invalid absolute target pattern `vendor\libsqlite3-sys-0.25.2\sqlite3/bindgen_bundled_version.rs` is not allowed: Expected a `:`, a trailing `/...` or the literal `...`.
                Error when treated as a path: expected a normalized path but got an un-normalized path instead: `vendor\libsqlite3-sys-0.25.2\sqlite3/bindgen_bundled_version.rs`
```

Notice how, due to `reindeer buckify` being run from a Windows host, it produced:

```
mapped_srcs = {
    "vendor\\libsqlite3-sys-0.25.2\\sqlite3/bindgen_bundled_version.rs": "vendor/libsqlite3-sys-0.25.2/src/bindgen.rs",
}
```

instead of the intended:

```
mapped_srcs = {
    "vendor/libsqlite3-sys-0.25.2/sqlite3/bindgen_bundled_version.rs": "vendor/libsqlite3-sys-0.25.2/src/bindgen.rs",
}
```

Reviewed By: zertosh

Differential Revision: D45612459

fbshipit-source-id: 041e6ee1d59eb45a53c8304dc854cae16a6f0602