Make buildifier not produce labels incompatible with Buck
Summary:
By default, `buildifier` normalizes labels in a way that assumes Bazel's behavior around labels. For example this dependency:

https://www.internalfb.com/code/fbsource/[9e3de4c453c817edc917f87d4c20e7822206dca3]/third-party/rust/BUCK?lines=12102%2C12104-12105

gets normalized from `//third-party/capstone:capstone` into `//third-party/capstone` because those mean the same same thing to Bazel. However, that's not compatible with Buck, so it's problematic for users of reindeer outside of fbsource.

```
error: fail: rule name must contain exactly one ":": "//third-party/capstone"
  --> tools/build_defs/fbcode_macros/build_defs/lib/target_utils.bzl:41:9
   |
41 |         fail('rule name must contain exactly one ":": "{}"'.format(target))
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Reviewed By: zertosh, diliop

Differential Revision: D41806885

fbshipit-source-id: 2d62fe5614518941abcff9defc6c7b5d4a4ff721