Update erased-serde from 0.4.8 to 0.4.9
Summary:
This release contains a fix relevant to this code in context-mesh-service:

https://www.internalfb.com/code/fbsource/[0bee62f6a8745be236e0e180ea8a4c69d4d282ac]/fbcode/frl/conductor/services/context-mesh/lib/mysql_repository.rs?lines=831-833%2C835-842

```lang=log,counterexample
error[E0505]: cannot move out of `json_serializer` because it is borrowed
   --> fbcode/frl/conductor/services/context-mesh/lib/mysql_repository.rs:838:23
    |
832 |         let mut json_serializer = serde_json::Serializer::new(writer);
    |             ------------------- binding `json_serializer` declared here
833 |         let erased_serializer = &mut <dyn Serializer>::erase(&mut json_serializer);
    |                                      ---------------------------------------------
    |                                      |                       |
    |                                      |                       borrow of `json_serializer` occurs here
    |                                      a temporary with access to the borrow is created here ...
...
838 |             .and_then(|_| {
    |                       ^^^ move out of `json_serializer` occurs here
839 |                 String::from_utf8(json_serializer.into_inner())
    |                                   --------------- move occurs due to use in closure
...
843 |     }
    |     - ... and the borrow might be used here, when that temporary is dropped and runs the destructor for type `impl erased_serde::Serializer`
```

Previously, `json_serializer` and `erased_serializer` were required to drop in reverse order of construction. In 0.4.9 they are allowed to drop in either order.

Reviewed By: cjlongoria

Differential Revision: D86491088

fbshipit-source-id: 125698b0806ddc6ceeb585f8b2ffa58e604190f4