Support extra_mapped_srcs fixup in vendor=false mode
Summary:
This fixes the following build error in {D46583909}:

```
root//:buck2 (prelude//platforms:default#524f8da68ea2a374): failed:
  Error running analysis for `root//:buck2 (prelude//platforms:default#524f8da68ea2a374)`

  Caused by:
      0: Error looking up configured node root//:buck2 (prelude//platforms:default#524f8da68ea2a374)
      1: Error looking up configured node root//app/buck2:buck2-bin (prelude//platforms:default#524f8da68ea2a374)
      2: Error looking up configured node shim//third-party/rust:anyhow (prelude//platforms:default#524f8da68ea2a374)
      3: looking up unconfigured target node `shim//third-party/rust:anyhow`
      4: Error loading targets in package `shim//third-party/rust` for target `shim//third-party/rust:anyhow`
      5: Error evaluating build file: `shim//third-party/rust:BUCK`
      6: Traceback (most recent call last):
           * shim/third-party/rust/BUCK:6194, in <module>
               cargo.rust_library(
           * prelude/rust/cargo_package.bzl:101, in _cargo_rust_library
               native.rust_library(name = name, **kwargs)
         error: Error coercing attribute `mapped_srcs` of `shim//third-party/rust:libsqlite3-sys-0.26.0`
            --> prelude/rust/cargo_package.bzl:101:5
             |
         101 |     native.rust_library(name = name, **kwargs)
             |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
             |

         Error coercing attribute `mapped_srcs` of `shim//third-party/rust:libsqlite3-sys-0.26.0`

         Caused by:
             0: Error coercing attribute `mapped_srcs` of type `attrs.dict(attrs.source(), attrs.string(), sorted=False, default={})`
             1: Error coercing {"../../../../../../var/twsvcscm/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libsqlite3-sys-0.26.0/sqlite3/bindgen_bundled_version.rs": "../../../../../../var/twsvcscm/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libsqlite3-sys-0.26.0/src/bindgen.rs"}
             2: Error coercing "../../../../../../var/twsvcscm/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libsqlite3-sys-0.26.0/sqlite3/bindgen_bundled_version.rs"
             3: Couldn't coerce `../../../../../../var/twsvcscm/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libsqlite3-sys-0.26.0/sqlite3/bindgen_bundled_version.rs` as a source.
                  Error when treated as a target: Invalid absolute target pattern `../../../../../../var/twsvcscm/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libsqlite3-sys-0.26.0/sqlite3/bindgen_bundled_version.rs` is not allowed: Expected a `:`, a trailing `/...` or the literal `...`.
                  Error when treated as a path: expected a normalized path but got an un-normalized path instead: `../../../../../../var/twsvcscm/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libsqlite3-sys-0.26.0/sqlite3/bindgen_bundled_version.rs`
```

Generated BUCK for libsqlite3-sys before this diff:

```
http_archive(
    name = "libsqlite3-sys-0.26.0.crate",
    sha256 = "afc22eff61b133b115c6e8c74e818c628d6d5e7a502afea6f64dee076dd94326",
    strip_prefix = "libsqlite3-sys-0.26.0",
    sub_targets = [
        "sqlite3/sqlite3.c",
        "sqlite3/sqlite3.h",
        "sqlite3/sqlite3ext.h",
        "sqlite3/wasm32-wasi-vfs.c",
    ],
    urls = ["https://crates.io/api/v1/crates/libsqlite3-sys/0.26.0/download"],
    visibility = [],
)

cargo.rust_library(
    name = "libsqlite3-sys-0.26.0",
    srcs = [":libsqlite3-sys-0.26.0.crate"],
    crate = "libsqlite3_sys",
    crate_root = "libsqlite3-sys-0.26.0.crate/src/lib.rs",
    edition = "2018",
    env = {
        "OUT_DIR": ".",
    },
    features = [
        "bundled",
        "bundled_bindings",
        "cc",
        "default",
        "min_sqlite_version_3_14_0",
        "pkg-config",
        "vcpkg",
    ],
    platform = {
        "linux-arm64": dict(
            mapped_srcs = {
                "../../../../../../home/david/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libsqlite3-sys-0.26.0/sqlite3/bindgen_bundled_version.rs": "../../../../../../home/david/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libsqlite3-sys-0.26.0/src/bindgen.rs",
            },
            deps = [":libsqlite3-sys-0.26.0-sqlite3"],
        ),
        "linux-x86_64": dict(
            mapped_srcs = {
                "../../../../../../home/david/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libsqlite3-sys-0.26.0/sqlite3/bindgen_bundled_version.rs": "../../../../../../home/david/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libsqlite3-sys-0.26.0/src/bindgen.rs",
            },
            deps = [":libsqlite3-sys-0.26.0-sqlite3"],
        ),
        "macos-arm64": dict(
            mapped_srcs = {
                "../../../../../../home/david/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libsqlite3-sys-0.26.0/sqlite3/bindgen_bundled_version.rs": "../../../../../../home/david/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libsqlite3-sys-0.26.0/src/bindgen.rs",
            },
            deps = [":libsqlite3-sys-0.26.0-sqlite3"],
        ),
        "macos-x86_64": dict(
            mapped_srcs = {
                "../../../../../../home/david/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libsqlite3-sys-0.26.0/sqlite3/bindgen_bundled_version.rs": "../../../../../../home/david/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libsqlite3-sys-0.26.0/src/bindgen.rs",
            },
            deps = [":libsqlite3-sys-0.26.0-sqlite3"],
        ),
        "windows-gnu": dict(
            mapped_srcs = {
                "fixups/libsqlite3-sys/overlay-windows/src/bindgen.rs": "../../../../../../home/david/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libsqlite3-sys-0.26.0/src/bindgen.rs",
            },
            deps = ["//third-party/rust/fixups/libsqlite3-sys/windows_x86_64_msvc-0.32.0-windows.lib:windows.lib"],
        ),
        "windows-msvc": dict(
            mapped_srcs = {
                "fixups/libsqlite3-sys/overlay-windows/src/bindgen.rs": "../../../../../../home/david/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libsqlite3-sys-0.26.0/src/bindgen.rs",
            },
            deps = ["//third-party/rust/fixups/libsqlite3-sys/windows_x86_64_msvc-0.32.0-windows.lib:windows.lib"],
        ),
    },
    visibility = [],
)
```

After this diff:

```
http_archive(
    name = "libsqlite3-sys-0.26.0.crate",
    sha256 = "afc22eff61b133b115c6e8c74e818c628d6d5e7a502afea6f64dee076dd94326",
    strip_prefix = "libsqlite3-sys-0.26.0",
    sub_targets = [
        "sqlite3/bindgen_bundled_version.rs",
        "sqlite3/sqlite3.c",
        "sqlite3/sqlite3.h",
        "sqlite3/sqlite3ext.h",
        "sqlite3/wasm32-wasi-vfs.c",
    ],
    urls = ["https://crates.io/api/v1/crates/libsqlite3-sys/0.26.0/download"],
    visibility = [],
)

cargo.rust_library(
    name = "libsqlite3-sys-0.26.0",
    srcs = [":libsqlite3-sys-0.26.0.crate"],
    crate = "libsqlite3_sys",
    crate_root = "libsqlite3-sys-0.26.0.crate/src/lib.rs",
    edition = "2018",
    env = {
        "OUT_DIR": ".",
    },
    features = [
        "bundled",
        "bundled_bindings",
        "cc",
        "default",
        "min_sqlite_version_3_14_0",
        "pkg-config",
        "vcpkg",
    ],
    platform = {
        "linux-arm64": dict(
            mapped_srcs = {
                ":libsqlite3-sys-0.26.0.crate[sqlite3/bindgen_bundled_version.rs]": "libsqlite3-sys-0.26.0.crate/src/bindgen.rs",
            },
            deps = [":libsqlite3-sys-0.26.0-sqlite3"],
        ),
        "linux-x86_64": dict(
            mapped_srcs = {
                ":libsqlite3-sys-0.26.0.crate[sqlite3/bindgen_bundled_version.rs]": "libsqlite3-sys-0.26.0.crate/src/bindgen.rs",
            },
            deps = [":libsqlite3-sys-0.26.0-sqlite3"],
        ),
        "macos-arm64": dict(
            mapped_srcs = {
                ":libsqlite3-sys-0.26.0.crate[sqlite3/bindgen_bundled_version.rs]": "libsqlite3-sys-0.26.0.crate/src/bindgen.rs",
            },
            deps = [":libsqlite3-sys-0.26.0-sqlite3"],
        ),
        "macos-x86_64": dict(
            mapped_srcs = {
                ":libsqlite3-sys-0.26.0.crate[sqlite3/bindgen_bundled_version.rs]": "libsqlite3-sys-0.26.0.crate/src/bindgen.rs",
            },
            deps = [":libsqlite3-sys-0.26.0-sqlite3"],
        ),
        "windows-gnu": dict(
            mapped_srcs = {
                "fixups/libsqlite3-sys/overlay-windows/src/bindgen.rs": "libsqlite3-sys-0.26.0.crate/src/bindgen.rs",
            },
            deps = ["//third-party/rust/fixups/libsqlite3-sys/windows_x86_64_msvc-0.32.0-windows.lib:windows.lib"],
        ),
        "windows-msvc": dict(
            mapped_srcs = {
                "fixups/libsqlite3-sys/overlay-windows/src/bindgen.rs": "libsqlite3-sys-0.26.0.crate/src/bindgen.rs",
            },
            deps = ["//third-party/rust/fixups/libsqlite3-sys/windows_x86_64_msvc-0.32.0-windows.lib:windows.lib"],
        ),
    },
    visibility = [],
)
```

Reviewed By: zertosh

Differential Revision: D46624305

fbshipit-source-id: 8223e7c78269cc8408412b3dd1401bc088aa3878